from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Dict, List, Tuple

from sqlalchemy import Boolean, Column, Integer, String, create_engine, select
from sqlalchemy.orm import declarative_base, sessionmaker

from app.core.config import settings


def _env(name: str, default: str = "") -> str:
    val = os.environ.get(name)
    if val is None:
        try:
            val = getattr(settings, name)
        except Exception:
            val = None
    return str(val if val is not None else default)


def _bool_env(name: str, default: bool = False) -> bool:
    val = _env(name, "1" if default else "0").strip().lower()
    return val in {"1", "true", "yes", "on", "y"}


def _quote_yaml(value: str) -> str:
    # Single-quote YAML scalar, escaping single quote by doubling it.
    return "'" + str(value).replace("'", "''") + "'"


def build_camera_rtsp_url(ip: str) -> str:
    template = _env("RTSP_URL_TEMPLATE", "rtsp://{username}:{password}@{ip}:{port}/video/live?channel={channel}&subtype={subtype}")
    vals = {
        "scheme": _env("RTSP_SCHEME", "rtsp"),
        "username": _env("RTSP_USERNAME", "") or _env("RTSP_USER", "admin"),
        "password": _env("RTSP_PASSWORD", "") or _env("RTSP_PASS", ""),
        "ip": str(ip or "").strip(),
        "port": _env("RTSP_PORT", "554"),
        "path": _env("RTSP_PATH", "/video/live"),
        "channel": _env("RTSP_CHANNEL", "1"),
        "subtype": _env("RTSP_SUBTYPE", "0"),
        "stream": _env("RTSP_STREAM", ""),
    }
    try:
        return template.format(**vals)
    except Exception:
        return f"rtsp://{vals['username']}:{vals['password']}@{vals['ip']}:{vals['port']}{vals['path']}?channel={vals['channel']}&subtype={vals['subtype']}"


def load_active_cameras_from_db() -> List[Dict[str, Any]]:
    db_url = str(_env("DATABASE_URL", "")).strip()
    if not db_url:
        raise RuntimeError("DATABASE_URL is empty; cannot generate MediaMTX camera paths")

    BaseLocal = declarative_base()

    class CameraRow(BaseLocal):
        __tablename__ = "cameras"
        id = Column(Integer, primary_key=True)
        name = Column(String)
        ip_address = Column(String)
        is_active = Column(Boolean)

    engine = create_engine(db_url, pool_pre_ping=True)
    Session = sessionmaker(bind=engine)
    rows: List[Dict[str, Any]] = []
    try:
        with Session() as session:
            for r in session.execute(select(CameraRow.id, CameraRow.name, CameraRow.ip_address, CameraRow.is_active)).all():
                try:
                    cam_id = int(r[0])
                except Exception:
                    continue
                active = bool(r[3]) if r[3] is not None else True
                if not active:
                    continue
                ip = str(r[2] or "").strip()
                if not ip:
                    continue
                rows.append({"id": cam_id, "name": str(r[1] or f"Camera {cam_id}"), "ip_address": ip})
    finally:
        try:
            engine.dispose()
        except Exception:
            pass
    rows.sort(key=lambda x: int(x["id"]))
    return rows


def build_mediamtx_config(cameras: List[Dict[str, Any]]) -> str:
    public_ip = _env("MEDIAMTX_PUBLIC_IP", "").strip() or _env("PUBLIC_IP", "").strip() or "164.52.214.233"
    write_queue = _env("MEDIAMTX_WRITE_QUEUE_SIZE", "256")
    source_on_demand = _bool_env("MEDIAMTX_SOURCE_ON_DEMAND", False)
    on_demand_str = "yes" if source_on_demand else "no"
    rtsp_transport = _env("MEDIAMTX_CAMERA_RTSP_TRANSPORT", "tcp") or "tcp"

    # IMPORTANT: sourceOnDemand must NOT be placed in pathDefaults because
    # pathDefaults also applies to publisher paths such as tracked/cam<ID>, ai/cam<ID>,
    # playback_cam<ID>. MediaMTX rejects sourceOnDemand on source: publisher paths.
    lines: List[str] = []
    lines.append("################################################")
    lines.append("# AUTO-GENERATED BY FastAPI from cameras table")
    lines.append("# Do not hard-code live/cam paths here; edit DB cameras instead.")
    lines.append("################################################")
    lines.append("logLevel: info")
    lines.append("logDestinations: [stdout, file]")
    lines.append("logFile: mediamtx.log")
    lines.append("readTimeout: 30s")
    lines.append("writeTimeout: 30s")
    lines.append(f"writeQueueSize: {write_queue}")
    lines.append("")
    lines.append("authMethod: internal")
    lines.append("authInternalUsers:")
    lines.append("  - user: any")
    lines.append("    pass:")
    lines.append("    ips: []")
    lines.append("    permissions:")
    lines.append("      - action: publish")
    lines.append("      - action: read")
    lines.append("      - action: playback")
    lines.append("  - user: any")
    lines.append("    pass:")
    lines.append("    ips: ['127.0.0.1', '::1']")
    lines.append("    permissions:")
    lines.append("      - action: api")
    lines.append("      - action: metrics")
    lines.append("      - action: pprof")
    lines.append("")
    lines.append("api: yes")
    lines.append("apiAddress: :9997")
    lines.append("playback: yes")
    lines.append("")
    lines.append("rtsp: yes")
    lines.append("rtspAddress: :8554")
    lines.append("protocols: [tcp]")
    lines.append("encryption: 'no'")
    lines.append("rtspAuthMethods: [basic]")
    lines.append("")
    lines.append("hls: yes")
    lines.append("hlsAddress: :8888")
    lines.append("hlsAllowOrigin: '*'")
    lines.append("hlsVariant: fmp4")
    lines.append("hlsSegmentCount: 4")
    lines.append("hlsSegmentDuration: 1s")
    lines.append("")
    lines.append("webrtc: yes")
    lines.append("webrtcAddress: :8889")
    lines.append("webrtcEncryption: no")
    lines.append("webrtcLocalUDPAddress: :8189")
    lines.append("webrtcLocalTCPAddress: :8189")
    lines.append(f"webrtcAdditionalHosts: [{_quote_yaml(public_ip)}]")
    lines.append("webrtcAllowOrigin: '*'")
    lines.append("")
    lines.append("rtmp: no")
    lines.append("srt: no")
    lines.append("")
    lines.append("pathDefaults:")
    lines.append("  maxReaders: 0")
    lines.append(f"  rtspTransport: {rtsp_transport}")
    lines.append("")
    lines.append("paths:")

    for cam in cameras:
        cam_id = int(cam["id"])
        name = str(cam.get("name") or f"Camera {cam_id}")
        ip = str(cam.get("ip_address") or "")
        url = build_camera_rtsp_url(ip)
        lines.append(f"  live/cam{cam_id}:")
        lines.append(f"    # {name} | {ip}")
        lines.append(f"    source: {_quote_yaml(url)}")
        lines.append(f"    rtspTransport: {rtsp_transport}")
        if source_on_demand:
            lines.append(f"    sourceOnDemand: {on_demand_str}")
            lines.append("    sourceOnDemandStartTimeout: 15s")
            lines.append("    sourceOnDemandCloseAfter: 5s")
        lines.append("")

    lines.append("  '~^ai/cam[0-9]+$':")
    lines.append("    source: publisher")
    lines.append("  '~^tracked/cam[0-9]+$':")
    lines.append("    source: publisher")
    lines.append("  '~^playback_cam[0-9]+$':")
    lines.append("    source: publisher")
    lines.append("  '~^playback_trace_.*$':")
    lines.append("    source: publisher")
    lines.append("  all_others:")
    lines.append("    source: publisher")
    lines.append("")
    return "\n".join(lines)

def maybe_generate_mediamtx_config() -> Tuple[bool, str]:
    if not _bool_env("MEDIAMTX_AUTOCONFIG", True):
        return False, "MEDIAMTX_AUTOCONFIG disabled"
    path = Path(_env("MEDIAMTX_CONFIG_PATH", "/root/mediamtx.yml")).expanduser()
    cams = load_active_cameras_from_db()
    data = build_mediamtx_config(cams)
    path.parent.mkdir(parents=True, exist_ok=True)
    old = path.read_text(encoding="utf-8") if path.exists() else ""
    if old == data:
        msg = f"[MEDIAMTX-AUTO] config already up to date: {path} ({len(cams)} cameras)"
        print(msg)
        return False, msg
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(data, encoding="utf-8")
    os.replace(str(tmp), str(path))
    msg = f"[MEDIAMTX-AUTO] wrote {path} with {len(cams)} DB camera paths live/cam<ID>"
    print(msg)
    for cam in cams[:20]:
        print(f"[MEDIAMTX-AUTO] live/cam{int(cam['id'])} <- {cam.get('ip_address')} ({cam.get('name')})")
    if len(cams) > 20:
        print(f"[MEDIAMTX-AUTO] ... {len(cams) - 20} more cameras")
    return True, msg
